add_transaction:
  fields:
    account_id:
      required: true
      selector:
        text:
    amount:
      required: true
      selector:
        number:
          min: -999999999
          max: 999999999
          step: 0.01
          mode: box
    note:
      selector:
        text:

adjust_balance:
  fields:
    account_id:
      required: true
      selector:
        text:
    new_balance:
      required: true
      selector:
        number:
          min: -999999999
          max: 999999999
          step: 0.01
          mode: box

add_plan:
  fields:
    account_id:
      required: true
      selector:
        text:
    title:
      required: true
      selector:
        text:
    amount:
      required: true
      selector:
        number:
          min: -999999999
          max: 999999999
          step: 1
          mode: box
    frequency:
      required: true
      selector:
        select:
          options:
            - "daily"
            - "weekly"
            - "monthly"
            - "yearly"
    day:
      required: true
      selector:
        number:
          min: 1
          max: 28
          mode: box
    month:
      default: 1
      selector:
        number:
          min: 1
          max: 12
          mode: box
    active:
      default: true
      selector:
        boolean:

update_plan:
  fields:
    account_id:
      required: true
      selector:
        text:
    plan_id:
      required: true
      selector:
        text:
    title:
      selector:
        text:
    amount:
      selector:
        number:
          min: -999999999
          max: 999999999
          step: 1
          mode: box
    frequency:
      selector:
        select:
          options:
            - "daily"
            - "weekly"
            - "monthly"
            - "yearly"
    day:
      selector:
        number:
          min: 1
          max: 28
          mode: box
    month:
      selector:
        number:
          min: 1
          max: 12
          mode: box
    active:
      selector:
        boolean:

delete_plan:
  fields:
    account_id:
      required: true
      selector:
        text:
    plan_id:
      required: true
      selector:
        text:

set_plan_active:
  fields:
    account_id:
      required: true
      selector:
        text:
    plan_id:
      required: true
      selector:
        text:
    active:
      required: true
      selector:
        boolean:
